service: microservice-template

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'stage'}
  logRetentionInDays: 30

plugins:
  - serverless-prune-plugin
  - "@vingle/serverless-tag-plugin"

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  helloAsync:
    handler: handlers.helloAsync
    events:
      - http:
          path: hello
          method: get
